name: Pack as legacy add-on

on:
  workflow_dispatch:

env:
  FILES: |
    __init__.py
    api_router.py
    auto_load.py
    file_formats.py
    operators/__init__.py
    operators/common.py
    operators/operator_color.py
    operators/operator_fill.py
    operators/operator_io_assets.py
    operators/operator_io_paste.py
    operators/operator_io_raster.py
    operators/operator_io_render.py
    operators/operator_line.py
    operators/operator_mesh.py
    operators/operator_polygon.py
    operators/operator_polygon_shading.py
    operators/operator_rig.py
    preferences.py
    res/icons/ops.nijigp.boolean_eraser_tool.dat
    res/icons/ops.nijigp.offset_tool.dat
    res/icons/ops.nijigp.smart_fill_tool.dat
    res/icons/ops.nijigp.sweep_tool.dat
    res/library.blend
    res/tex/metal_shiny.exr
    res/tex/ToonWater.png
    resources.py
    solvers/fit.py
    solvers/graph.py
    solvers/measure.py
    solvers/optimizer.py
    tmp/placeholder
    ui_panels.py
    ui_viewport_tools.py
    utils.py

jobs:
  pick_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy required files
        run: |
          for file in $FILES; do
            mkdir -p "artifact/nijigp/$(dirname "$file")"
            cp "$file" "artifact/nijigp/$file"
          done

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: nijigp
          path: artifact
